spring:
  application:
    name: "Notes-Server"

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: validate

  sql:
    init:
      mode: never

  web:
    locale: en_US

logging:
  level:
    root: info
    com.jimmy_d.notesserver: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  error:
    include-stacktrace: never