spring:
  application:
    name: "Notes-Server"

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: validate

  sql:
    init:
      mode: always

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
        stat: debug
        cache: debug
        SQL_SLOW: debug

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"