spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5433/postgres
    username: postgres
    password: pass

  sql:
    init:
      mode: never

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  file:
    path: "log/app.log"
  logback:
    rollingpolicy:
      clean-history-on-start: false
      max-file-size: 10MB
      file-name-pattern: log/app.%d{yyyy-MM-dd}.%i.gz
      max-history: 7
      total-size-cap: 100MB
