spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: never

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS}


logging:
  file:
    path: "log/app.log"
  logback:
    rollingpolicy:
      clean-history-on-start: false
      max-file-size: 10MB
      file-name-pattern: log/app.%d{yyyy-MM-dd}.%i.gz
      max-history: 7
      total-size-cap: 100MB
